import { App, FileSystemAdapter, Platform } from "obsidian";

interface SystemError {
	code?: string;
}

interface ExecException extends Error {
	cmd?: string;
	killed?: boolean;
	code?: number | string;
	signal?: string;
}

interface ChildProcessLib {
	exec: (
		command: string,
		callback: (
			error: ExecException | null,
			stdout: string,
			stderr: string,
		) => void,
	) => void;
}

interface ElectronWindow {
	require(module: "child_process"): ChildProcessLib;
}

export class IgnoreManager {
	app: App;
	ignoreFile = ".stignore";

	constructor(app: App) {
		this.app = app;
	}

	async ensureDefaults() {
		const exists = await this.app.vault.adapter.exists(this.ignoreFile);
		if (!exists) {
			const configDir = this.app.vault.configDir;
			const defaultContent = `
            # --- Generated by Syncthing Controller ---
            # Ignora configurações de janela/workspace
            ${configDir}/workspace*

            # Ignora cache de instalador
            ${configDir}/installer.json
            `.trim();

			try {
				await this.saveIgnoreFile(defaultContent);
			} catch {
				/* ... */
			}
		}
	}

	async readIgnoreFile(): Promise<string> {
		if (await this.app.vault.adapter.exists(this.ignoreFile)) {
			return await this.app.vault.adapter.read(this.ignoreFile);
		}
		return "";
	}

	async saveIgnoreFile(content: string) {
		try {
			await this.app.vault.adapter.write(this.ignoreFile, content);
		} catch (error) {
			const sysError = error as SystemError;
			if (
				(sysError.code === "EPERM" || sysError.code === "EACCES") &&
				Platform.isWin
			) {
				await this.forceWriteWindows(content);
			} else {
				throw error;
			}
		}
	}

	private async forceWriteWindows(content: string) {
		const adapter = this.app.vault.adapter;

		if (!(adapter instanceof FileSystemAdapter)) {
			throw new Error(
				"O adaptador de arquivos não suporta acesso ao caminho completo (Mobile?).",
			);
		}

		const fullPath = adapter.getFullPath(this.ignoreFile);

		await this.runCmd(`attrib -h "${fullPath}"`);

		try {
			await adapter.write(this.ignoreFile, content);
		} finally {
			await this.runCmd(`attrib +h "${fullPath}"`).catch((err) =>
				console.error("Falha ao re-ocultar .stignore", err),
			);
		}
	}

	private runCmd(command: string): Promise<void> {
		return new Promise((resolve, reject) => {
			const win = window as unknown as ElectronWindow;
			const { exec } = win.require("child_process");

			exec(command, (error) => {
				if (error) {
					reject(error);
				} else {
					resolve();
				}
			});
		});
	}
}
