import { App } from 'obsidian';

export class IgnoreManager {
    app: App;
    ignoreFile = '.stignore';

    constructor(app: App) {
        this.app = app;
    }

    async ensureDefaults() {
        const exists = await this.app.vault.adapter.exists(this.ignoreFile);
        if (!exists) {
            const configDir = this.app.vault.configDir;
            const defaultContent = `
            # --- Generated by Syncthing Controller ---
            # Ignora configurações de janela/workspace
            ${configDir}/workspace*

            # Ignora cache de instalador
            ${configDir}/installer.json
            `.trim();

            try {
                await this.app.vault.adapter.write(this.ignoreFile, defaultContent);
            } catch { /* ... */ }
        }
    }

    async readIgnoreFile(): Promise<string> {
        if (await this.app.vault.adapter.exists(this.ignoreFile)) {
            return await this.app.vault.adapter.read(this.ignoreFile);
        }
        return ''; 
    }

    async saveIgnoreFile(content: string) {
        await this.app.vault.adapter.write(this.ignoreFile, content);
    }
}